apiVersion: v1
kind: Service
metadata:
  name: mail-api
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    aplicacion: mail-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30456
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    aplicacion: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30211
---
apiVersion: v1
kind: Service
metadata:
  name: mail-server
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    aplicacion: mail-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
      nodePort: 30222
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30203
      name: smtp